# Generated by Django 6.1 on 2026-08-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_product_created_at_product_delivery_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_categories',
            field=models.ManyToManyField(related_name='sub_categories', to='catalog.category'),
        ),
    ]
